apiVersion: batch/v1
kind: Job
metadata:
  name: pydjango-5
  namespace: serverless
  labels:
    app: pydjango-5
spec:
  template:
    metadata:
      labels:
        app: pydjango-5
    spec:
      containers:
      - name: pydjango-5
        image: apurvchaudhary/pydjango:1.0.1
      restartPolicy: Never
  backoffLimit: 3
