# Generated by Django 5.1.4 on 2024-12-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerlessFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DEPLOYED', 'Deployed'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
